### ISSUE TITLE
URLs not behaving as 'expected'

### ISSUE THREAD

**Issue by delightedbydhamma** [suttacentral/suttacentral#3310] opened 2024-11-05 23:49 UTC
#### Description:
https://suttacentral.net/sutta goes to DN
https://suttacentral.net/vinaya goes Theravada bhikkhu vinaya
https://suttacentral.net/abhidhamma goes to Theravada abhidhamma

#### Expected behaviour:

I would have expected them to go to 
https://suttacentral.net/pitaka/sutta
https://suttacentral.net/pitaka/vinaya
https://suttacentral.net/pitaka/abhidhamma
respectively

**Comment by thesunshade** [comment] 2024-11-06 00:02
On those first three links, scroll down. For example the first one goes to a page with every single sutta. It's huge.

That is the expected, but probably useless, behaviour. It's like how https://suttacentral.net/pitaka/sutta/long/dn will take you to the top level DN page (showing three vaggas) but https://suttacentral.net/dn takes you to a page will all the DN suttas.

Basically the pages in your first list are a feature, not a bug. Although pages will all children are kind of useless at the top level like that.

**Comment by ihongda** [comment] 2024-11-14 14:43
I have fixed this problem, will close this issue 🙏🏼

**Closed as completed by ihongda** 2024-11-14 14:43 UTC
