### ISSUE TITLE
[Firefox] Pali /Chinese look ups: switch on when moving to new page

### ISSUE THREAD

**Issue by SamaneriVimala** [suttacentral/suttacentral#768] opened 2018-03-26 00:00 UTC
Original ticket Creator:
malgorzata.maksimczyk

Reported by Vimala:

When I turn on the pali or chinese lookups in the text-settings, it does not always stay on when a new page is selected. For instance, go to any random pali page, scroll to the bottom, click NEXT and then it does not work any more. On the segmented texts it is not so bad but on the html-texts this always happens. Same with the chinese.

Jira ID: SUCE-393
Jira Creation Date: 20/Dec/17 11:02 AM
Jira Epic: 
Jira Priority: High
Jira Status (at import): Selected For Development

Comments:
 
01/Jan/18 11:20 PM;ayya.vimala;Also the font changes when doing next/prev.

The error might at least be partly due to an error in the .po files where the language is wrongly defined. When I change this in the console to `pli-Latn` the font changes correctly.
{quote}#. <html><head><meta charset="utf8"><meta content="Pali text from the
 #. Mahāsaṅgīti Tipiṭaka Buddhavasse 2500"
 #. name="description"><title></title></head><body><div id="text"
 #. *lang="pi"*><section class="sutta" id="dn1"><article><div class="hgroup"><p
 #. class="division">
{quote}
 

On the `simple-text` pages however, a simple reload of the page after clicking next/prev seems to work.
26/Feb/18 1:14 PM;krzysztof.wozniak;Pali look ups works properly. With Chinese look ups are still problems, look ups not working after using "Previous/Next" functionality.
26/Feb/18 8:55 PM
ayya.vimala
Pali lookup does not work either for legacy texts. For segmented texts it seems to work.
01/Mar/18 2:28 PM;krzysztof.wozniak;Pali lookups still doesn't work on legacy and also Chinese lookups on FireFox browser.

 

On others seems to work good.

**Comment by SamaneriVimala** [comment] 2018-03-26 21:26
Only still on Firefox.

**Comment by sujato** [comment] 2018-10-13 12:09
To confirm, this is still an issue with FF 62.

**Comment by Aminah-SC** [comment] 2018-12-13 11:40
@sujato please add links to this ticket as Robert doesn't know how to reproduce it.

**Comment by sujato** [comment] 2019-01-02 06:09
Cannot reproduce, closing.

**Closed by sujato** 2019-01-02 06:09 UTC
Labels: Blakish, STX, Type: bug
