### ISSUE TITLE
Yellow Brick Road broken for non-English languages

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1548] opened 2019-11-25 08:05 UTC
The purpose of the Yellow Brick Road (AKA Little Green Dots) is to indicate in the sidebar where there are translations in the user’s selected language. A green dot appears on menu items that include relevant translations.

Currently it works for English, but for other languages, no green dots are displayed.

**The sidebar should display green dots to indicate translations in the user’s selected language.**

**Comment by chansikpark** [comment] 2019-11-25 08:17
## Investigation notes:

Inspecting the network log, the green dots are modulated by a boolean attribute called "yellow_brick_road" in the API call "/api/menu?language=". In English, the values return true while returning false when it's not. This indicates that the issue involves the back end.

A full search for "yellow_brick_road" yields the function that appears to be solely responsible for YBR:
```
    def make_yellow_brick_road(self, menu_entries, language):
        is_submenu_yellow_brick_road = False
        for entry in menu_entries:
            if 'uid' in entry:
                uid = entry['uid'].split('/', 1)[1]
            else:
                uid = entry['id']

            is_entry_yellow_brick = has_translated_descendent(uid, language)
            if 'children' in entry:
                is_entry_yellow_brick += self.make_yellow_brick_road(
                    entry['children'], language
                )
            entry['yellow_brick_road'] = bool(is_entry_yellow_brick)
            is_submenu_yellow_brick_road += is_entry_yellow_brick
        return is_submenu_yellow_brick_road
```

This function calls another function that makes a critical query "AVAILABLE_TRANSLATIONS_LIST":

```
// First collect all distinct text uids
LET text_uids = (
    FOR doc IN v_text
        SEARCH doc.lang == @lang
        RETURN DISTINCT doc.uid
)

// Now collect their distinct parent documents
LET parents = (
    FOR uid IN text_uids
        LET doc = DOCUMENT('root', uid)
        FILTER doc
        FOR v, e, p IN 1..1 INBOUND doc `root_edges`
            RETURN DISTINCT v
)

// Now get the uids for those parents and all anscestors
LET parent_uids = (
    FOR doc IN parents
        FOR v, e, p IN 0..10 INBOUND doc `root_edges`
            RETURN v.uid
)

RETURN SORTED_UNIQUE(UNION(parent_uids, text_uids))
```

Presumably the problem is somewhere around here.

**Comment by ihongda** [comment] 2019-11-26 00:44
Thanks for Chan's careful work, the version of ArangoDB was indeed updated some time ago, after your analysis, it is very likely that the update of the version caused some problems, including the yellow brick road and the language page showing incomplete.

**Comment by chansikpark** [comment] 2019-11-26 15:10
An additional note for posterity: 

One hypothesis for the underlying issue is that there was/is flaky support for ArangoSearch Views with links into two tables. 

To demonstrate, this is a screenshot of /languages/pli when things are broken:

![Screenshot from 2019-11-26 23-58-33](https://user-images.githubusercontent.com/16063972/69645294-4caac980-10a9-11ea-9ae7-4f0ce0f53984.png)

It looks like only the segmented texts seem to have been showing. This is what it's supposed to look like:

![Screenshot from 2019-11-26 23-58-57](https://user-images.githubusercontent.com/16063972/69645407-782db400-10a9-11ea-83a3-de358349f379.png)

The query for this page, and for YBR uses `v_text` which has "links" into both `po_strings` and `html_text`.

The definition is this:
```
db.create_view(
    'v_text',
    view_type='arangosearch',
    properties={
        'links': {
            'html_text': {
                'fields': {
                    'uid': {'analyzers': ['identity']},
                    'lang': {'analyzers': ['identity']},
                }
            },
            'po_strings': {
                'fields': {
                    'uid': {'analyzers': ['identity']},
                    'lang': {'analyzers': ['identity']},
                }
            },
        }
    },
)
```

Whatever the case, if this issue flares up again, just another clue for the mystery.

**Comment by chansikpark** [comment] 2019-11-27 04:40
Confirmed fixed on staging.

(1) Set language to Afrikaans:
![Screenshot from 2019-11-27 13-32-26](https://user-images.githubusercontent.com/16063972/69694047-e8c0e900-111a-11ea-99da-a32ee85e8869.png)

(2) YBR on Sutta:
![Screenshot from 2019-11-27 13-32-262](https://user-images.githubusercontent.com/16063972/69694066-f5ddd800-111a-11ea-8c94-17b264bbd6c9.png)

(3) YBR on Khuddakanikaya:
![Screenshot from 2019-11-27 13-33-10](https://user-images.githubusercontent.com/16063972/69694093-08581180-111b-11ea-9e8c-656cb6c9c0f5.png)

(4) On Suttanipata:
![Screenshot from 2019-11-27 13-33-37](https://user-images.githubusercontent.com/16063972/69694100-1148e300-111b-11ea-934b-80210a01de5b.png)

(5) On all vaggas:
![Screenshot from 2019-11-27 13-34-08](https://user-images.githubusercontent.com/16063972/69694107-19a11e00-111b-11ea-8ea8-20e880cb5ba6.png)

(6) Language page for Afrikaans (/languages/af):
![image](https://user-images.githubusercontent.com/16063972/69694198-59680580-111b-11ea-9e77-aa692d31bd32.png)

**Closed** 2019-11-30 16:14 UTC
