### ISSUE TITLE
Review webpack production config

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#1971] opened 2021-02-10 06:32 UTC
It's been 2 years (!) since we've updated production, and we have made many changes.

We need to check that old webpack production config and make sure it works with the new site.

See https://github.com/suttacentral/suttacentral/pull/1974/files

**Comment by robertmusil** [comment] 2021-02-10 11:31
Kinda duplicate of #1680

**Comment by sujato** [comment] 2021-02-10 11:51
Except with this one, it's really just about checking to see that it works.

If we can use a new bundler, great! But probably a bunch of work, no?

**Comment by robertmusil** [comment] 2021-02-10 12:25
I mean, switching to new webpack is also an option.

**Closed** 2021-03-11 22:53 UTC
