### ISSUE TITLE
PWA review

### ISSUE THREAD

**Issue by sujato** [suttacentral/suttacentral#2685] opened 2023-05-30 09:55 UTC
It has been several years since we looked at the PWA functionality. We should do a careful review to ensure it is working as well as possible.

- investigate modern PWA standards and ensure compliance
- bug test on as many devices as possible
- review performance on low-end devices and networks
- review strategy for downloads, consider optimizing

See several discussions on Discourse, such as:

https://discourse.suttacentral.net/t/an-inconvenient-pwa-offline-behavior/29289

**Comment by thesunshade** [comment] 2024-02-28 20:49
I'm closing this as a duplicate of https://github.com/suttacentral/suttacentral/issues/2600

**Closed as not planned by thesunshade** 2024-02-28 20:49 UTC
Labels: Type: improvement
